# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db-tests:
    image: postgres:14
    restart: always
    container_name: integration-tests-fnv
    ports:
      - '${DATABASE_TESTS_PORT}:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  db-dev:
    image: postgres:14
    restart: always
    container_name: dev-fnv
    ports:
      - '${DATABASE_DEV_PORT}:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
